image: debian:testing-slim

# caching apt
# To avoid to dl everything each time
cache:
  key: "apt-cache"
  paths:
    - apt-cache

build:
  stage: build
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y install context wget unzip make asymptote
  script:
    - make get-fonts
    - make
  artifacts:
    paths:
      - a-*/*.svg
      - a-*/*.gif
      - a-*/*.pdf
