sudo: required
dist: bionic
- sudo apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y context wget unzip make asymptote fonts-dejavu

before_install:

script:
- make get-fonts
- make
- make pages
